/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restapi

type LenderPool struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	Token string `json:"token"`

	Decimals int64 `json:"decimals"`

	TokenAddress string `json:"tokenAddress"`

	Lender string `json:"lender"`

	LenderWrap string `json:"lenderWrap"`

	Reserve float32 `json:"reserve"`

	Fees float32 `json:"fees"`
}
