/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restapi

type MultiSwapExec struct {

	Token string `json:"token,omitempty"`

	Decimals int64 `json:"decimals,omitempty"`

	TokenAddress string `json:"tokenAddress,omitempty"`

	Lenderwrap string `json:"lenderwrap,omitempty"`

	Lender string `json:"lender,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Swaps []SwapExec `json:"swaps,omitempty"`
}
