/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SwapPool struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	Token0 int32 `json:"token0"`

	Token1 int32 `json:"token1"`

	Reserve0 int32 `json:"reserve0"`

	Reserve1 int32 `json:"reserve1"`

	Rate int32 `json:"rate"`

	Fees int32 `json:"fees"`
}
