/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restapi

type MultiSwapExecSigned struct {

	Transactoin string `json:"transactoin,omitempty"`
}
