/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package restapi

type SwapExec struct {

	Token0 string `json:"token0"`

	Token1 string `json:"token1"`

	Decimals0 int64 `json:"decimals0"`

	Decimals1 int64 `json:"decimals1"`

	Token0Address string `json:"token0Address"`

	Token1Address string `json:"token1Address"`

	Amount float32 `json:"amount"`

	SwapWrap string `json:"swapWrap,omitempty"`

	Pool string `json:"pool,omitempty"`
}
