/*
 * Arth-Arbitrage
 *
 * Arth Arbitrage API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LenderPool struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	Token int32 `json:"token"`

	Reserve int32 `json:"reserve"`

	Fees int32 `json:"fees"`
}
